-- MySQL Script generated by MySQL Workbench
-- 04/06/17 20:04:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OASystem
-- -----------------------------------------------------
-- OA办公系统数据库

-- -----------------------------------------------------
-- Schema OASystem
--
-- OA办公系统数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OASystem` DEFAULT CHARACTER SET utf8 ;
USE `OASystem` ;

-- -----------------------------------------------------
-- Table `OASystem`.`t_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OASystem`.`t_admin` (
  `id` BIGINT(20) NOT NULL COMMENT '主键ID，32位长度字符串，数据库自动生成',
  `username` VARCHAR(255) NOT NULL COMMENT '登录用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '登录密码',
  `realname` VARCHAR(45) NOT NULL COMMENT '真实姓名',
  `sex` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '性别 0：男、1：女',
  `mobile` VARCHAR(45) NULL COMMENT '手机号码',
  `email` VARCHAR(255) NULL COMMENT '邮箱',
  `createTime` MEDIUMTEXT NOT NULL COMMENT '创建时间',
  `updateTime` MEDIUMTEXT NOT NULL COMMENT '更新时间',
  `createBy` BIGINT(20) NOT NULL COMMENT '创建者Id',
  INDEX `fk_t_admin_t_admin_idx` (`createBy` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_t_admin_t_admin`
    FOREIGN KEY (`createBy`)
    REFERENCES `OASystem`.`t_admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
